services:
  php:
    build:
      context: docker/php
    volumes:
      - .:/app
    ports:
      - '8080:8080'
  mongodb:
    image: mongo:3.6
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
      - .:/app
