security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        session_rss:
            pattern: ^/sessions/rss
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Trainer"
                provider: fos_userbundle

    access_control:
        - { path: ^/, roles: ROLE_USER }
